POST http://localhost:3003/api/users
Content-Type: application/json

{
    "first_name":"yovel",
    "last_name":"hadad",
    "id":1223,
    "birthday":"21/8/1996"
}
###

GET http://localhost:3003/api/users
###

POST http://localhost:3003/addcost
Content-Type: application/json

{
    "user_id":123123,
    "year": 2023,
    "month":5,
    "day":12,
    "description":"milk",
    "category":"food",
    "sum":8
}
###